export const products = [
  {
    productid: 1,
    name: "Product 1",
    description: "Description 1",
    imgSrc: "main-1.jpg",
    price: 725,
    genre: "merch",
  },
  {
    productid: 2,
    name: "Product 2",
    description: "Description 2",
    imgSrc: "main-2.jpg",
    price: 821,
    genre: "tech",
  },
  {
    productid: 3,
    name: "Product 3",
    description: "Description 3",
    imgSrc: "main-3.jpg",
    price: 912,
    genre: "merch",
  },
  {
    productid: 4,
    name: "Product 4",
    description: "Description 4",
    imgSrc: "main-4.jpg",
    price: 664,
    genre: "tech",
  },
  {
    productid: 5,
    name: "Product 5",
    description: "Description 5",
    imgSrc: "main-5.jpg",
    price: 745,
    genre: "merch",
  },
  {
    productid: 6,
    name: "Product 6",
    description: "Description 6",
    imgSrc: "main-6.jpg",
    price: 853,
    genre: "tech",
  },
  {
    productid: 7,
    name: "Product 7",
    description: "Description 7",
    imgSrc: "main-1.jpg",
    price: 732,
    genre: "merch",
  },
  {
    productid: 8,
    name: "Product 8",
    description: "Description 8",
    imgSrc: "main-1.jpg",
    price: 865,
    genre: "tech",
  },
  {
    productid: 9,
    name: "Product 9",
    description: "Description 9",
    imgSrc: "main-1.jpg",
    price: 745,
    genre: "merch",
  },
  {
    productid: 10,
    name: "Product 10",
    description: "Description 10",
    imgSrc: "main-1.jpg",
    price: 900,
    genre: "tech",
  },
  {
    productid: 11,
    name: "Product 11",
    description: "Description 11",
    imgSrc: "main-1.jpg",
    price: 740,
    genre: "merch",
  },
  {
    productid: 12,
    name: "Product 12",
    description: "Description 12",
    imgSrc: "main-1.jpg",
    price: 805,
    genre: "tech",
  },
  {
    productid: 13,
    name: "Product 13",
    description: "Description 13",
    imgSrc: "main-1.jpg",
    price: 770,
    genre: "merch",
  },
  {
    productid: 14,
    name: "Product 14",
    description: "Description 14",
    imgSrc: "main-1.jpg",
    price: 845,
    genre: "tech",
  },
  {
    productid: 15,
    name: "Product 15",
    description: "Description 15",
    imgSrc: "main-1.jpg",
    price: 712,
    genre: "merch",
  },
  {
    productid: 16,
    name: "Product 16",
    description: "Description 16",
    imgSrc: "main-1.jpg",
    price: 880,
    genre: "tech",
  },
  {
    productid: 17,
    name: "Product 17",
    description: "Description 17",
    imgSrc: "main-1.jpg",
    price: 754,
    genre: "merch",
  },
  {
    productid: 18,
    name: "Product 18",
    description: "Description 18",
    imgSrc: "main-1.jpg",
    price: 800,
    genre: "tech",
  },
  {
    productid: 19,
    name: "Product 19",
    description: "Description 19",
    imgSrc: "main-1.jpg",
    price: 725,
    genre: "merch",
  },
  {
    productid: 20,
    name: "Product 20",
    description: "Description 20",
    imgSrc: "main-1.jpg",
    price: 835,
    genre: "tech",
  },
  {
    productid: 21,
    name: "Product 21",
    description: "Description 21",
    imgSrc: "main-1.jpg",
    price: 745,
    genre: "merch",
  },
  {
    productid: 22,
    name: "Product 22",
    description: "Description 22",
    imgSrc: "main-1.jpg",
    price: 840,
    genre: "tech",
  },
  {
    productid: 23,
    name: "Product 23",
    description: "Description 23",
    imgSrc: "main-1.jpg",
    price: 755,
    genre: "merch",
  },
  {
    productid: 24,
    name: "Product 24",
    description: "Description 24",
    imgSrc: "main-1.jpg",
    price: 810,
    genre: "tech",
  },
  {
    productid: 25,
    name: "Product 25",
    description: "Description 25",
    imgSrc: "main-1.jpg",
    price: 725,
    genre: "merch",
  },
  {
    productid: 26,
    name: "Product 26",
    description: "Description 26",
    imgSrc: "main-1.jpg",
    price: 860,
    genre: "tech",
  },
  {
    productid: 27,
    name: "Product 27",
    description: "Description 27",
    imgSrc: "main-1.jpg",
    price: 775,
    genre: "merch",
  },
  {
    productid: 28,
    name: "Product 28",
    description: "Description 28",
    imgSrc: "main-1.jpg",
    price: 825,
    genre: "tech",
  },
  {
    productid: 29,
    name: "Product 29",
    description: "Description 29",
    imgSrc: "main-1.jpg",
    price: 765,
    genre: "merch",
  },
  {
    productid: 30,
    name: "Product 30",
    description: "Description 30",
    imgSrc: "main-1.jpg",
    price: 850,
    genre: "tech",
  },
];

export const user = {
  userid: 1,
  username: "mich12",
  email: "michael@email.com",
  firstName: "Michael",
  lastName: "Shirma",
  role: "user",
  balance: 5642,
};

export const product = {
  productid: 10,
  name: "Product10",
  imgSrc: "main-1.jpg",
  price: 75,
  genre: "merch",
};

export const backet = {
  userid: 1,
  listBacket: [{}],
};
